### ISSUE TITLE
Plasma datasets 

### ISSUE THREAD

**Issue by ypriverol** [multiomics/multiomics-configs#171]
- [PXD017052](https://github.com/multiomics/multiomics-configs/tree/master/projects/plasma-proteomes/PXD017052)
    - [Analyzed DDA](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/absolute-expression/PXD017052.1/)
    - [Analyzed DIA](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/absolute-expression/PXD017052.2/)
- PXD029009 - [Analyzed](https://github.com/multiomics/multiomics-configs/tree/master/projects/plasma-proteomes/PXD029009)
- [PXD010899](https://github.com/multiomics/multiomics-configs/tree/master/projects/plasma-proteomes/PXD010899)
   - [Analyzed LFQ](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/absolute-expression/PXD010899.1/)
   - [Analyzed TMT](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/absolute-expression/PXD010899.2/)
- [PXD013231](https://github.com/multiomics/multiomics-configs/tree/master/projects/plasma-proteomes/PXD013231)
   - [Analyzed DDA](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/absolute-expression/PXD013231.1/)
   - [Analyzed DIA](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/absolute-expression/PXD013231.2/)
- [PXD004242](https://github.com/multiomics/multiomics-configs/blob/master/projects/plasma-proteomes/PXD004242/PXD004242.sdrf.tsv) - [Analyzed](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/absolute-expression/PXD004242/)
- PXD008467 - [Analyzed](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/absolute-expression/PXD008467)
- PXD008468 - [Analyzed](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/absolute-expression/PXD008468)
- [PXD009348](https://github.com/multiomics/multiomics-configs/tree/master/projects/plasma-proteomes/PXD009348) 
   - [Analyzed DDA](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/absolute-expression/PXD009348.1) 
- [PXD036609](https://github.com/multiomics/multiomics-configs/blob/master/projects/plasma-proteomes/PXD036609/PXD036609.sdrf.tsv) - [Analyzed](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/absolute-expression/PXD036609/)
- [PXD023650](https://github.com/multiomics/multiomics-configs/blob/master/projects/plasma-proteomes/PXD023650/PXD023650.sdrf.tsv) - [Analyzed](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/absolute-expression/PXD023650/)
- [PXD022469](https://github.com/multiomics/multiomics-configs/blob/master/projects/plasma-proteomes/PXD022469/PXD022469.sdrf.tsv) - [Analyzed](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/absolute-expression/PXD022469/)
- [PXD019817](https://github.com/multiomics/multiomics-configs/blob/master/projects/plasma-proteomes/PXD019817/PXD019817.sdrf.tsv) - [Analyzed](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/absolute-expression/PXD019817/)
- [PXD017834](https://github.com/multiomics/multiomics-configs/tree/master/projects/plasma-proteomes/PXD017834)
   - [Analyzed LFQ](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/absolute-expression/PXD017834.1/)
   - [Analyzed TMT](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/absolute-expression/PXD017834.2/) 
- [PXD011839](https://github.com/multiomics/multiomics-configs/tree/master/projects/plasma-proteomes/PXD011839) - [Analyzed](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/absolute-expression/PXD011839)
- [PXD002854](https://github.com/multiomics/multiomics-configs/tree/master/projects/plasma-proteomes/PXD002854)
   - [Analyzed serum](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/absolute-expression/PXD002854.1)
   - [Analyzed plasma](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/absolute-expression/PXD002854.3)
   - [Analyzed erythrocyte](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/absolute-expression/PXD002854.2) 
- PXD006559 - [Analyzed TMT](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/absolute-expression/PXD006559)
- PXD017976
- PXD039023 - [Analyzed](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/absolute-expression/PXD039023/)
- PXD027463 (Paper requested, pending response in ResearchGate)
- PXD038674 - [Analyzed](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/absolute-expression/PXD038674)
- PXD038669
  - [Analyzed DDA](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/absolute-expression/PXD038669.1)
  - [Analyzed DIA](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/absolute-expression/PXD038669.2) 
- PXD038526 - [Analyzed](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/absolute-expression/PXD038526)
- PXD011482
- PXD020727 - [Analyzed](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/absolute-expression/PXD020727)
- PXD037340 
   - [Analyzed DDA](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/absolute-expression/PXD037340.1)
   - [Analyzed DIA](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/absolute-expression/PXD037340-DIA) - Error in conversion https://github.com/bigbio/quantms/issues/268 
- PXD030598 - [Analyzed](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/absolute-expression/PXD030598/) 
- PXD018874
- PXD040438 - [Analyzed](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/absolute-expression/PXD040438/)
- PXD009219 - [Analyzed](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/absolute-expression/PXD009219/)
- PXD008441 - [Analyzed](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/absolute-expression/PXD008441)
- PXD037682 - [Analyzed](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/absolute-expression/PXD037682)
- PXD027125 - [Analyzed](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/absolute-expression/PXD027125)
- MSV000079033
   - [Analyzed TMT6](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/absolute-expression/MSV000079033.1)
   -  [Analyzed TMT10](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/absolute-expression/MSV000079033.2)
   - [Analyzed ITRAQ](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/absolute-expression/MSV000079033.3)
   - [Analyzed ITRAQ - Supermix](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/absolute-expression/MSV000079033.4)
   - [Analyzed ITRAQ Ipg14](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/absolute-expression/MSV000079033.5)

**Comment by ypriverol** [comment]
@daichengxin, @asierlarrea would be helping also to annotate datasets.

**Comment by asierlarrea** [comment]
PXD008467 and PXD008468: TMT, need help annotating individuals, replicates etc
PXD006559: Only platelets, no plasma. TMT, need help annotating individuals, replicates etc
PXD011797: Odd labeling, better remove from list
PXD017976: (Done, 14 samples). Few samples, only platelets
PXD038674: (Done, 63 samples)
PXD038669:
-DIA: (Done, 144 samples) Missing modification values (oxidation etc)
-DDA: (Done, 9 samples) Few samples, missing modification values

**Comment by asierlarrea** [comment]
PXD029009: A lot of missing data about patients. We will contact the authors.
PXD038526: (Done) Missing modification values (oxidation etc)

**Comment by asierlarrea** [comment]
PXD011482: I think I've managed to annotate a TMT!!! 180 files, 1900 samples

**Comment by asierlarrea** [comment]
PXD020727: (Done) 42 files

**Comment by asierlarrea** [comment]
PXD004352: (Done) 365 files, but only immune system cells, not plasma. Not sure if experiments in different cell lines correspond to the same individual or each file is a unique individual

**Comment by asierlarrea** [comment]
PXD004678: Only dentritic cells, no plasma. Not a priority for now

**Comment by ypriverol** [comment]
@asierlarrea This one looks really nice: PXD008441

**Comment by asierlarrea** [comment]
Ok, I will annotate it

**Comment by asierlarrea** [comment]
@daichengxin, can you help me with TMT annotation? In some cases I would say there is no way of knowing what patienta has each label, or what conditions are tested in a .raw file. I tried to look for it in the supplementary files, but I cannot find it. The TMT datasets are PXD006559, PXD008468 and PXD008467. Thank you very much!

**Comment by ypriverol** [comment]
> @daichengxin, can you help me with TMT annotation? In some cases I would say there is no way of knowing what patienta has each label, or what conditions are tested in a .raw file. I tried to look for it in the supplementary files, but I cannot find it. The TMT datasets are PXD006559, PXD008468 and PXD008467. Thank you very much!

DONE

**Comment by ypriverol** [comment]
I will close this issue now.
