### ISSUE TITLE
Error converting to OpenMS experimental Design 

### ISSUE THREAD

**Issue by ypriverol** [multiomics/multiomics-configs#9]
@daichengxin: 

The following sdrf https://github.com/multiomics/multiomics-configs/blob/master/datasets/absolute-expression/tissues/PXD004242/PXD004242-Sample-1.tsv when is converted to OpenMS experimental design don't pick the technical replicates. Instead is using 1,1,1,1 . 

Can you have a look.

**Comment by daichengxin** [comment]
The technical replicate column name is written as the characteristics attribute

**Comment by ypriverol** [comment]
Problem solved!!!
